import PDFDocument from 'pdfkit';

// Reporting Catalogue — PRD Section 17. Real PDF generation (not a stub);
// "Generate Report" produces an actual formatted, downloadable document
// within seconds, per the NFR in Section 11.1 ("under 30 seconds").

const NAVY = '#0b2545';
const GOLD = '#c9972d';
const GREY = '#555555';

function streamToBuffer(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

function header(doc: PDFKit.PDFDocument, title: string, subtitle: string, classification: string) {
  doc.rect(0, 0, doc.page.width, 70).fill(NAVY);
  doc.fillColor('#ffffff').fontSize(16).font('Helvetica-Bold').text('ZACC INSTITUTIONAL COMPLIANCE PORTAL', 40, 20);
  doc.fillColor(GOLD).fontSize(9).font('Helvetica').text('Prevention & Corporate Governance Department', 40, 42);
  doc.fillColor('#ffffff').fontSize(9).text(classification, 40, 42, { align: 'right', width: doc.page.width - 80 });
  doc.moveDown(3);
  doc.fillColor(NAVY).fontSize(18).font('Helvetica-Bold').text(title, 40, 90);
  doc.fillColor(GREY).fontSize(10).font('Helvetica').text(subtitle, 40, 114);
  doc.moveTo(40, 134).lineTo(doc.page.width - 40, 134).strokeColor(GOLD).lineWidth(1.5).stroke();
  doc.moveDown(2);
  doc.y = 150;
}

function footer(doc: PDFKit.PDFDocument) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc
      .fontSize(8)
      .fillColor(GREY)
      .text(
        `Generated by ZACC Institutional Compliance Portal on ${new Date().toLocaleString()} — Page ${i + 1} of ${range.count}`,
        40,
        doc.page.height - 40,
        { align: 'center', width: doc.page.width - 80 }
      );
  }
}

function sectionTitle(doc: PDFKit.PDFDocument, text: string) {
  doc.moveDown(0.5);
  doc.fontSize(13).fillColor(NAVY).font('Helvetica-Bold').text(text);
  doc.moveDown(0.3);
}

function kvRow(doc: PDFKit.PDFDocument, label: string, value: string) {
  doc.fontSize(10).font('Helvetica-Bold').fillColor('#222222').text(label + ': ', { continued: true }).font('Helvetica').text(value);
}

function ragColor(rag: string): string {
  if (rag === 'Green') return '#16a34a';
  if (rag === 'Amber') return '#d97706';
  return '#dc2626';
}

export interface AssessmentReportData {
  institutionName: string;
  institutionType: string;
  province: string;
  officerName: string;
  assessmentDate: string;
  status: string;
  sectionScores: Record<string, number | null>;
  compositeScore: number;
  ragStatus: string;
  narrative: string;
  nonCompliantItems: { section: string; item_text: string; comments: string | null }[];
  recommendations: { description: string; owner_name: string | null; due_date: string }[];
}

export async function buildAssessmentReportPdf(data: AssessmentReportData): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
  header(doc, 'Compliance Assessment Report', data.institutionName, 'CONFIDENTIAL — Internal ZACC Use');

  sectionTitle(doc, 'Institution Details');
  kvRow(doc, 'Institution', data.institutionName);
  kvRow(doc, 'Type', data.institutionType);
  kvRow(doc, 'Province', data.province);
  kvRow(doc, 'Assessing Officer', data.officerName);
  kvRow(doc, 'Assessment Date', data.assessmentDate);
  kvRow(doc, 'Status', data.status);

  sectionTitle(doc, 'Weighted Compliance Score');
  Object.entries(data.sectionScores).forEach(([k, v]) => {
    kvRow(doc, capitalize(k), v !== null && v !== undefined ? `${v.toFixed(1)}/100` : 'Not scored');
  });
  doc.moveDown(0.3);
  doc.fontSize(12).font('Helvetica-Bold').fillColor(NAVY).text(`Composite Score: ${data.compositeScore.toFixed(1)}/100`);
  doc.fontSize(12).font('Helvetica-Bold').fillColor(ragColor(data.ragStatus)).text(`Status: ${data.ragStatus}`);

  sectionTitle(doc, 'Executive Narrative');
  doc.fontSize(10).font('Helvetica').fillColor('#222222').text(data.narrative, { align: 'justify' });

  if (data.nonCompliantItems.length > 0) {
    sectionTitle(doc, 'Findings Requiring Attention');
    data.nonCompliantItems.forEach((item, i) => {
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#222222').text(`${i + 1}. [${capitalize(item.section)}] ${item.item_text}`);
      if (item.comments) doc.fontSize(9).font('Helvetica-Oblique').fillColor(GREY).text(`   Officer comments: ${item.comments}`);
    });
  }

  if (data.recommendations.length > 0) {
    sectionTitle(doc, 'Implementation Matrix (Auto-Generated Recommendations)');
    data.recommendations.forEach((r, i) => {
      doc.fontSize(10).font('Helvetica').fillColor('#222222').text(`${i + 1}. ${r.description}  —  Owner: ${r.owner_name ?? 'Institution Focal Person'}  —  Due: ${r.due_date}`);
    });
  }

  footer(doc);
  return streamToBuffer(doc);
}

export interface ScorecardData {
  institutionName: string;
  province: string;
  sector: string;
  riskLevel: string;
  latestScore: number | null;
  latestRag: string | null;
  assessmentHistory: { date: string; score: number; rag: string }[];
  openRecommendations: number;
  closedRecommendations: number;
  openRisks: { name: string; category: string; score: number }[];
}

export async function buildScorecardPdf(data: ScorecardData): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
  header(doc, 'Institutional Scorecard', data.institutionName, 'CONFIDENTIAL — Internal & Approved Donor Use Only');

  sectionTitle(doc, 'Profile');
  kvRow(doc, 'Institution', data.institutionName);
  kvRow(doc, 'Province', data.province);
  kvRow(doc, 'Sector', data.sector);
  kvRow(doc, 'Risk Classification', data.riskLevel);
  kvRow(doc, 'Latest Compliance Score', data.latestScore !== null ? `${data.latestScore.toFixed(1)}/100 (${data.latestRag})` : 'No assessments yet');

  sectionTitle(doc, 'Assessment History');
  data.assessmentHistory.forEach((h) => {
    doc.fontSize(10).font('Helvetica').fillColor('#222222').text(`${h.date}:  ${h.score.toFixed(1)}/100  —  `, { continued: true });
    doc.font('Helvetica-Bold').fillColor(ragColor(h.rag)).text(h.rag);
  });
  if (data.assessmentHistory.length === 0) doc.fontSize(10).fillColor(GREY).text('No prior assessments recorded.');

  sectionTitle(doc, 'Recommendation Closure');
  kvRow(doc, 'Open Recommendations', String(data.openRecommendations));
  kvRow(doc, 'Closed Recommendations', String(data.closedRecommendations));
  const total = data.openRecommendations + data.closedRecommendations;
  const rate = total > 0 ? ((data.closedRecommendations / total) * 100).toFixed(1) : 'N/A';
  kvRow(doc, 'Closure Rate', total > 0 ? `${rate}%` : 'N/A');

  sectionTitle(doc, 'Open Corruption Risks');
  if (data.openRisks.length === 0) {
    doc.fontSize(10).fillColor(GREY).text('No open risks recorded.');
  } else {
    data.openRisks.forEach((r) => {
      doc.fontSize(10).fillColor('#222222').text(`${r.name} [${r.category}] — Score ${r.score}/25`);
    });
  }

  footer(doc);
  return streamToBuffer(doc);
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
